source 'https://rubygems.org'

group :development do
  gem 'bundler', '~> 1.11'
  gem 'byebug', '~> 8.2'
  gem 'rake', '~> 12.3'

  gem 'guard', '~> 2.14'
  gem 'guard-minitest', '~> 2.4'
  gem 'guard-rubocop', '~> 1.3'
  gem 'minitest', '~> 5.0'
  gem 'minitest-reporters', '~> 1.1'
  gem 'rubocop', '~> 0.48'
end
