require 'rubygems'
require 'bundler'
begin
  Bundler.setup(:default, :development)
rescue Bundler::BundlerError => e
  warn e.message
  warn 'Run `bundle install` to install missing gems'
  exit e.status_code
end

require 'rake'

require 'rake/testtask'
Rake::TestTask.new(:test) do |test|
  test.libs << 'lib' << 'test'
  test.pattern = 'test/**/*_test.rb'
  test.verbose = true
end

require 'rubocop/rake_task'
RuboCop::RakeTask.new

desc 'Run all linters'
task lint: [:rubocop]

desc 'Run all tests and linters'
task check: %i[test rubocop]

task default: :check
