module ProcessedCsv
  def contacts_hash
    [
      {
        first_name: 'Glenda',
        last_name: 'Rosas',
        email: 'glendarrosas@dodgit.com',
        phone: '613-937-0694',
        address_line_1: '326 Donato Ridges',
        city: 'Rimbey',
        province: 'AB',
        country_name: 'Canada',
        postcode: 'T0C 2J0',
        date_added: '2015-02-24 1054:02 UTC',
        how_did_you_hear_about_us: 'Newspaper',
        what_is_your_budget: '$200-$299',
        what_is_your_favourite_color: 'Blue'
      },
      {
        first_name: 'Jennyfer',
        last_name: 'Pollich',
        email: 'jp79@shaw.me',
        phone: '(245) 024-5595',
        address_line_1: '2015 Arvid Locks',
        city: 'West Fredericstad',
        province: 'BC',
        country_name: 'Canada',
        postcode: 'V6B 3A0',
        date_added: '2014-01-16 1614:27 UTC',
        how_did_you_hear_about_us: 'Google',
        what_is_your_budget: '$100-$199',
        what_is_your_favourite_color: 'Blue'
      },
      {
        first_name: 'Woodrow',
        last_name: 'Brown',
        email: 'woodrowdbrown@mailinator.com',
        phone: '905-338-1135',
        address_line_1: '479 Ari Ridges',
        city: 'Terrace',
        province: 'BC',
        country_name: 'Canada',
        postcode: 'V8G 1S2',
        date_added: '2014-06-16 1329:08 UTC',
        how_did_you_hear_about_us: 'Google',
        what_is_your_budget: '$200-$299',
        what_is_your_favourite_color: 'Green'
      },
      {
        first_name: 'Kelly',
        last_name: 'Davis',
        email: 'kellywdavis@dodgit.com',
        phone: '905-371-5194',
        address_line_1: nil,
        city: nil,
        province: 'BC',
        country_name: 'Canada',
        postcode: 'V8C 1G3',
        date_added: '2014-02-19 2117:27 UTC',
        how_did_you_hear_about_us: nil,
        what_is_your_budget: nil,
        what_is_your_favourite_color: nil
      },
      {
        first_name: 'Scott',
        last_name: 'Fleming',
        email: 'scottmfleming@pookmail.com',
        phone: '905-303-8565',
        address_line_1: '327 Donato Ridges',
        city: 'New Westminster',
        province: 'BC',
        country_name: 'Canada',
        postcode: 'V3M 6A1',
        date_added: '2015-02-18 0854:43 UTC',
        how_did_you_hear_about_us: 'Newspaper',
        what_is_your_budget: '$200-$299',
        what_is_your_favourite_color: 'Blue'
      },
      {
        first_name: 'Woodrow',
        last_name: 'Brown',
        email: 'woodrowdbrown@mailinator.com',
        phone: '905-338-1135',
        address_line_1: '479 Ari Ridges',
        city: 'Terrace',
        province: 'BC',
        country_name: 'Canada',
        postcode: 'V8G 1S2',
        date_added: '2013-09-10 0830:19 UTC',
        how_did_you_hear_about_us: 'Newspaper',
        what_is_your_budget: '$200-$299',
        what_is_your_favourite_color: 'Green'
      },
      {
        first_name: 'Jeramy',
        last_name: 'Kling',
        email: 'jeramyk@telus.net',
        phone: '(618) 924-6290',
        address_line_1: '5287 Green Pines',
        city: 'Orvilleside',
        province: 'CO',
        country_name: 'USA',
        postcode: '91234',
        date_added: '2014-09-05 0109:22 UTC',
        how_did_you_hear_about_us: 'Google',
        what_is_your_budget: '$200-$299',
        what_is_your_favourite_color: 'Green'
      },
      {
        first_name: 'Lucille',
        last_name: 'Farr',
        email: 'lucillekfarr@spambob.com',
        phone: '250-363-9781',
        address_line_1: '9834 Haverford Drive',
        city: 'Winnipeg',
        province: 'MB',
        country_name: 'Canada',
        postcode: 'R3C 0C4',
        date_added: '2014-12-02 2133:33 UTC',
        how_did_you_hear_about_us: 'Google',
        what_is_your_budget: '$200-$299',
        what_is_your_favourite_color: 'Green'
      },
      {
        first_name: 'Kareem',
        last_name: 'Muller',
        email: 'kmuller@klinglemke.info',
        phone: '1-653-037-9985',
        address_line_1: '380 Haag Fords',
        city: 'East Jeremie',
        province: 'NWT',
        country_name: 'Canada',
        postcode: 'V6B 3A0',
        date_added: '2015-04-03 1553:42 UTC',
        how_did_you_hear_about_us: nil,
        what_is_your_budget: nil,
        what_is_your_favourite_color: nil
      },
      {
        first_name: 'Margaret',
        last_name: 'Padberg',
        email: 'magpads@gmail.com',
        phone: '(599) 684-9711',
        address_line_1: '325 Donato Ridges',
        city: 'Veumhaven',
        province: 'OH',
        country_name: 'USA',
        postcode: '51234',
        date_added: '2013-09-26 1106:00 UTC',
        how_did_you_hear_about_us: 'TV',
        what_is_your_budget: '$200-$299',
        what_is_your_favourite_color: 'Orange'
      },
      {
        first_name: 'Margaret',
        last_name: 'Padberg',
        email: 'magpads@gmail.com',
        phone: '(599) 684-9711',
        address_line_1: '325 Donato Ridges',
        city: 'Veumhaven',
        province: 'OH',
        country_name: 'USA',
        postcode: '51234',
        date_added: '2015-05-06 0832:21 UTC',
        how_did_you_hear_about_us: 'TV',
        what_is_your_budget: '$200-$299',
        what_is_your_favourite_color: 'Orange'
      },
      {
        first_name: 'Gregory',
        last_name: 'Wilson',
        email: 'ernestomwilson@dodgit.com',
        phone: '211-411-0987',
        address_line_1: '88 Ridgeford Crescent',
        city: 'Contra',
        province: 'OH',
        country_name: 'USA',
        postcode: '98735',
        date_added: '2013-08-19 0030:58 UTC',
        how_did_you_hear_about_us: 'Friend/Family',
        what_is_your_budget: '$300-$399',
        what_is_your_favourite_color: nil
      },
      {
        first_name: 'Richard',
        last_name: 'Robinson',
        email: 'richarderobinson@trashymail.com',
        phone: '403-843-0454',
        address_line_1: '381 Haag Fords',
        city: 'Kitchener',
        province: 'ON',
        country_name: 'Canada',
        postcode: 'N2H 5A5',
        date_added: '2014-07-29 0931:09 UTC',
        how_did_you_hear_about_us: nil,
        what_is_your_budget: nil,
        what_is_your_favourite_color: nil
      },
      {
        first_name: 'Debra',
        last_name: 'Littlefield',
        email: 'debramlittlefield@pookmail.com',
        phone: '418-763-1809',
        address_line_1: '5288 Green Pines',
        city: 'Hamilton',
        province: 'ON',
        country_name: 'Canada',
        postcode: 'L8P 1P8',
        date_added: '2014-10-20 1221:11 UTC',
        how_did_you_hear_about_us: 'TV',
        what_is_your_budget: '$100-$199',
        what_is_your_favourite_color: 'Orange'
      },
      {
        first_name: 'Stephen',
        last_name: 'Hope',
        email: 'stephenihope@mailinator.com',
        phone: '514-299-6949',
        address_line_1: '326 Donato Ridges',
        city: 'Cornwall',
        province: 'ON',
        country_name: 'Canada',
        postcode: 'K6J 3R2',
        date_added: '2013-07-22 2147:07 UTC',
        how_did_you_hear_about_us: 'Newspaper',
        what_is_your_budget: '$200-$299',
        what_is_your_favourite_color: 'Blue'
      },
      {
        first_name: 'Concetta',
        last_name: 'Bass',
        email: 'concettadbass@dodgit.com',
        phone: '905-256-7695',
        address_line_1: '9833 Haverford Drive',
        city: 'Oakville',
        province: 'ON',
        country_name: 'Canada',
        postcode: 'L6J 3X4',
        date_added: '2014-01-10 1049:10 UTC',
        how_did_you_hear_about_us: nil,
        what_is_your_budget: nil,
        what_is_your_favourite_color: nil
      },
      {
        first_name: 'Dolores',
        last_name: 'Sanders',
        email: 'dolorescsanders@spambob.com',
        phone: '905-243-7932',
        address_line_1: '382 Haag Fords',
        city: 'Niagara Falls',
        province: 'ON',
        country_name: 'Canada',
        postcode: 'L2E 4E6',
        date_added: '2013-06-15 0914:30 UTC',
        how_did_you_hear_about_us: nil,
        what_is_your_budget: nil,
        what_is_your_favourite_color: nil
      },
      {
        first_name: 'James',
        last_name: 'Barrier',
        email: 'jamesabarrier@mailinator.com',
        phone: '306-734-8379',
        address_line_1: '5289 Green Pines',
        city: 'Malton',
        province: 'ON',
        country_name: 'Canada',
        postcode: 'L4T 1A9',
        date_added: '2014-07-26 0934:08 UTC',
        how_did_you_hear_about_us: nil,
        what_is_your_budget: nil,
        what_is_your_favourite_color: nil
      },
      {
        first_name: 'Rhonda',
        last_name: 'Wellington',
        email: 'rhondaiwellington@pookmail.com',
        phone: '416-592-3319',
        address_line_1: '480 Ari Ridges',
        city: 'Welland',
        province: 'ON',
        country_name: 'Canada',
        postcode: 'L3B 3Z6',
        date_added: '2014-05-27 0001:54 UTC',
        how_did_you_hear_about_us: 'Google',
        what_is_your_budget: '$200-$299',
        what_is_your_favourite_color: 'Green'
      },
      {
        first_name: 'Teri',
        last_name: 'Battle',
        email: nil,
        phone: nil,
        address_line_1: '327 Donato Ridges',
        city: 'Oshawa',
        province: 'ON',
        country_name: 'Canada',
        postcode: 'L1G 6Z8',
        date_added: '2013-07-19 0633:18 UTC',
        how_did_you_hear_about_us: 'Newspaper',
        what_is_your_budget: '$200-$299',
        what_is_your_favourite_color: 'Blue'
      },
      {
        first_name: 'Frank',
        last_name: 'Summers',
        email: 'frankssummers@dodgit.com',
        phone: '204-298-8265',
        address_line_1: '480 Ari Ridges',
        city: 'Toronto',
        province: 'ON',
        country_name: 'Canada',
        postcode: 'M5T 1T4',
        date_added: '2015-01-05 1341:59 UTC',
        how_did_you_hear_about_us: 'Google',
        what_is_your_budget: '$300-$399',
        what_is_your_favourite_color: 'Red'
      },
      {
        first_name: 'James',
        last_name: 'Hopkins',
        email: 'jamesehopkins@spambob.com',
        phone: '250-385-4587',
        address_line_1: '2018 Arvid Locks',
        city: 'Maple',
        province: 'ON',
        country_name: 'Canada',
        postcode: 'L6A 1G5',
        date_added: '2014-05-14 0746:40 UTC',
        how_did_you_hear_about_us: 'Newspaper',
        what_is_your_budget: '$200-$299',
        what_is_your_favourite_color: 'Blue'
      },
      {
        first_name: 'Sarah',
        last_name: 'Abdul',
        email: 'meganawheeler@spambob.com',
        phone: '133-214-8255',
        address_line_1: '9832 Haverford Drive',
        city: 'Cambridge',
        province: 'PEI',
        country_name: 'Canada',
        postcode: 'T2A 1C8',
        date_added: '2014-02-19 1034:06 UTC',
        how_did_you_hear_about_us: nil,
        what_is_your_budget: nil,
        what_is_your_favourite_color: nil
      },
      {
        first_name: 'James',
        last_name: 'Morin',
        email: 'jameshmorin@pookmail.com',
        phone: '403-391-7787',
        address_line_1: '90 Ridgeford Crescent',
        city: 'Wheatley River',
        province: 'PEI',
        country_name: 'Canada',
        postcode: 'C1E 0M5',
        date_added: '2013-07-01 1441:49 UTC',
        how_did_you_hear_about_us: 'Google',
        what_is_your_budget: '$200-$299',
        what_is_your_favourite_color: 'Orange'
      },
      {
        first_name: 'Stephen',
        last_name: 'Robinson',
        email: 'stephenbrobinson@pookmail.com',
        phone: '250-631-8145',
        address_line_1: '479 Ari Ridges',
        city: 'St-Jerome',
        province: 'QC',
        country_name: 'Canada',
        postcode: 'J7Z 5T3',
        date_added: '2014-03-27 0539:28 UTC',
        how_did_you_hear_about_us: 'Google',
        what_is_your_budget: '$300-$399',
        what_is_your_favourite_color: 'Red'
      },
      {
        first_name: 'Mario',
        last_name: 'McLemore',
        email: 'mariojmclemore@mailinator.com',
        phone: '250-639-1043',
        address_line_1: '5288 Green Pines',
        city: 'Ste Anne Des Monts',
        province: 'QC',
        country_name: 'Canada',
        postcode: 'G4V 1B6',
        date_added: '2013-11-08 1725:07 UTC',
        how_did_you_hear_about_us: 'Google',
        what_is_your_budget: '$200-$299',
        what_is_your_favourite_color: 'Orange'
      },
      {
        first_name: 'Robert',
        last_name: 'Jacobs',
        email: 'robertajacobs@dodgit.com',
        phone: '905-733-9456',
        address_line_1: '2017 Arvid Locks',
        city: 'Montreal',
        province: 'QC',
        country_name: 'Canada',
        postcode: 'H2K 4J5',
        date_added: '2014-10-16 1900:03 UTC',
        how_did_you_hear_about_us: nil,
        what_is_your_budget: nil,
        what_is_your_favourite_color: nil
      },
      {
        first_name: 'Mario',
        last_name: 'McLemore',
        email: 'mariojmclemore@mailinator.com',
        phone: '250-639-1043',
        address_line_1: '5288
        Green Pines',
        city: 'Ste Anne Des Monts',
        province: 'QC',
        country_name: 'Canada',
        postcode: 'G4V 1B6',
        date_added: '2015-04-16 1741:04 UTC',
        how_did_you_hear_about_us: 'TV',
        what_is_your_budget: '$100-$199',
        what_is_your_favourite_color: 'Purple'
      },
      {
        first_name: 'Betty',
        last_name: 'Velez',
        email: 'bettyjvelez@spambob.com',
        phone: '450-675-7225',
        address_line_1: '2016 Arvid Locks',
        city: 'Zenon Park',
        province: 'SK',
        country_name: 'Canada',
        postcode: 'S0E 1W0',
        date_added: '2014-02-06 1113:25 UTC',
        how_did_you_hear_about_us: nil,
        what_is_your_budget: nil,
        what_is_your_favourite_color: nil
      },
      {
        first_name: 'John',
        last_name: 'Dunlap',
        email: 'johnedunlap@dodgit.com',
        phone: '902-964-6824',
        address_line_1: '5289 Green Pines',
        city: 'Craik',
        province: 'SK',
        country_name: 'Canada',
        postcode: 'S4P 3Y2',
        date_added: '2013-10-18 1701:04 UTC',
        how_did_you_hear_about_us: 'TV',
        what_is_your_budget: '$100-$199',
        what_is_your_favourite_color: 'Orange'
      },
      {
        first_name: 'Maye',
        last_name: 'Kessler',
        email: 'mkessler@welchandsons.net',
        phone: '775-007-9211',
        address_line_1: '478 Ari Ridges',
        city: 'Larkinbury',
        province: 'VT',
        country_name: 'USA',
        postcode: '87346',
        date_added: '2013-10-23 1602:53 UTC',
        how_did_you_hear_about_us: 'Newspaper',
        what_is_your_budget: '$200-$299',
        what_is_your_favourite_color: 'Blue'
      },
      {
        first_name: 'Maye',
        last_name: 'Kessler',
        email: 'mkessler@welchandsons.net',
        phone: '775-007-9211',
        address_line_1: '478 Ari Ridges',
        city: 'Larkinbury',
        province: 'VT',
        country_name: 'USA',
        postcode: '87346',
        date_added: '2014-12-04 1920:00 UTC',
        how_did_you_hear_about_us: 'Newspaper',
        what_is_your_budget: '$100-$199',
        what_is_your_favourite_color: 'Yellow'
      },
      {
        first_name: 'Jeramy',
        last_name: 'Kling',
        email: 'jeramyk@telus.net',
        phone: '(618) 924-6290',
        address_line_1: '5287 Green Pines',
        city: nil,
        province: nil,
        country_name: 'USA',
        postcode: '91234',
        date_added: '2013-07-26 0427:57 UTC',
        how_did_you_hear_about_us: 'Google',
        what_is_your_budget: '$200-$299',
        what_is_your_favourite_color: 'Green'
      }
    ]
  end
end
